apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: h2u7snjih-go 
  janus-idp.io/tekton: h2u7snjih-go
  backstage.io/kubernetes-id: h2u7snjih-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: h2u7snjih-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml