apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h2u7snjih-go
  janus-idp.io/tekton: h2u7snjih-go
  backstage.io/kubernetes-id: h2u7snjih-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: h2u7snjih-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
